DROP TABLE IF EXISTS TEST;
CREATE TABLE CORE_JAVA_DEFINITION
(
 ID NUMBER PRIMARY KEY, 
 DESCRIPTION VARCHAR(5000),
 DETAILS VARCHAR(10000),
 IMAGE_PATHS VARCHAR(10000)
);

CREATE SEQUENCE CORE_JAVA_SEQUENCE
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;
