DROP TABLE IF EXISTS CORE_JAVA_DEFINITION;

CREATE TABLE CORE_JAVA_DEFINITION
(
 ID NUMBER PRIMARY KEY, 
 DESCRIPTION VARCHAR(5000),
 DETAILS VARCHAR(10000),
 IMAGE_PATHS VARCHAR(10000)
);

CREATE SEQUENCE CORE_JAVA_SEQUENCE
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

DROP TABLE IF EXISTS APACHE_KAFKA_DEFINITION;

CREATE TABLE APACHE_KAFKA_DEFINITION
(
 ID NUMBER PRIMARY KEY, 
 DESCRIPTION VARCHAR(5000),
 DETAILS VARCHAR(10000),
 IMAGE_PATHS VARCHAR(10000)
);

CREATE SEQUENCE APACHE_KAFKA_SEQUENCE
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

DROP TABLE IF EXISTS GROOVY_DEFINITION;

CREATE TABLE GROOVY_DEFINITION
(
 ID NUMBER PRIMARY KEY, 
 DESCRIPTION VARCHAR(5000),
 DETAILS VARCHAR(10000),
 IMAGE_PATHS VARCHAR(10000)
);

CREATE SEQUENCE GROOVY_SEQUENCE
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;